Add route building control
mappable-world/mappable-default-ui-theme pull request #9
Opened 2024-05-16 14:11 UTC by matthew44-mappable

Fixes #

2024-06-20 12:48 UTC, xdan requested changes

2024-06-20 12:48 UTC, xdan commented on src/controls/MMapRouteControl/index.css
> +    &.error {
also

2024-06-20 12:48 UTC, xdan commented on src/controls/MMapRouteControl/index.ts
> +        this.addChild(this._control);
direct

2024-06-20 12:48 UTC, xdan commented on src/controls/MMapRouteControl/index.ts
> +        this._detachDom = undefined;
Again need remove children

2024-06-20 12:48 UTC, xdan commented on src/controls/MMapRouteControl/utils.ts
> +export function formatDistance(length: number): string {
metters: lengthMetters: or jsdoc

2024-06-24 09:08 UTC, matthew44-mappable commented on src/controls/MMapRouteControl/MMapWaypointInput/index.ts
> +        this._detachDom?.();
I moved the creation of entities to the constructor

2024-06-24 09:13 UTC, matthew44-mappable commented on src/controls/MMapRouteControl/MMapWaypointInput/index.ts
> +                this._indicator.insertAdjacentHTML('afterbegin', emptyIndicatorSVG);
I didn't quite understand the question and what the problem was. If the input field is empty, an indicator is displayed next to it, indicating an empty input field. This was described in the UI design 🤷‍♂️

2024-06-24 09:15 UTC, matthew44-mappable commented on src/controls/MMapRouteControl/MMapWaypointInput/index.ts
> +        this.removeChild(this._suggestComponent);
Why? We added `_suggestComponent` via the "addChild" method

2024-06-24 15:54 UTC, xdan commented on src/controls/MMapRouteControl/MMapWaypointInput/index.ts
> +                this._indicator.insertAdjacentHTML('afterbegin', emptyIndicatorSVG);
No, I'm talking about insertAdjacentHTML
Why is it needed? You have an empty DOM element
Just innerHTML?

2024-06-24 15:56 UTC, xdan commented on src/controls/MMapRouteControl/MMapWaypointInput/index.ts
> +        this.removeChild(this._suggestComponent);
use addDirectChild, What happens if your component is inserted into React? children in react will displace those you use inside

2024-06-24 16:25 UTC, matthew44-mappable commented on src/controls/MMapRouteControl/MMapWaypointInput/index.ts
> +        this.removeChild(this._suggestComponent);
Also fixed this it in the search control

2024-06-25 09:49 UTC, merged